services:
  db:
    image: postgres
    container_name: database
    volumes:
      - pgdbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
  backend:
    container_name: back
    command:  sh -c "gunicorn --bind 0.0.0.0:8000 backend.wsgi && 
              python3 manage.py collectstatic --noinput"
    build: .
    expose:
      - 8000
    volumes:
      - static-data:/vol/static
      - media-data:/vol/media
    depends_on:
      - db
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    depends_on: 
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx-conf
      - ./nginx/etc/ssl:/etc/nginx/ssl
      - static-data:/vol/static
      - media-data:/vol/media
volumes:
  pgdbdata:
  static-data:
  media-data: